import Link from 'next/link'
import { redirect } from 'next/navigation'
import MagicLinkForm from '@/components/MagicLinkForm'
import { createClient } from '@/lib/supabase/server'

export default async function ConsumerLogin() {
  const supabase = createClient()
  const { data } = await supabase.auth.getUser()
  if (data.user) {
    redirect('/consumer/dashboard')
  }

  return (
    <main className="mx-auto grid max-w-6xl gap-12 px-6 py-16 lg:grid-cols-[1.05fr_0.95fr]">
      <section>
        <Link href="/" className="heading-ui text-mist hover:text-gold">
          &larr; Back to landing
        </Link>
        <p className="heading-ui mt-8 text-gold">Consumer Portal</p>
        <h1 className="heading-display mt-4 text-5xl font-light text-bone">
          Enter Wellness.
        </h1>
        <p className="mt-6 max-w-xl text-mist">
          Your sovereign longevity record lives behind a magic link. No passwords to
          forget. Sign in to score your biological age, book Phase 1 protocols, and
          receive a daily insight generated by Claude.
        </p>
        <ul className="mt-10 space-y-3 text-sm text-bone">
          <li className="flex gap-3"><span className="text-gold">01.</span> Bio age in under two minutes.</li>
          <li className="flex gap-3"><span className="text-gold">02.</span> Eight Phase 1 protocols, priced and bookable.</li>
          <li className="flex gap-3"><span className="text-gold">03.</span> Membership tiers from free to Sovereign.</li>
          <li className="flex gap-3"><span className="text-gold">04.</span> AI-guided daily insight, refreshed every 20 hours.</li>
        </ul>
      </section>
      <section className="self-center">
        <MagicLinkForm portal="consumer" accent="gold" />
      </section>
    </main>
  )
}
