#!/usr/bin/env node
// Embeds public/index.html as a base64 string into a TypeScript module so
// the route handler at app/route.ts can return the wellness SPA without
// reading from the filesystem at request time. Filesystem reads on Vercel
// serverless functions are unreliable because process.cwd() does not always
// point at the project root. A bundled string is always available.
//
// Substitutes {{NEXT_PUBLIC_SUPABASE_URL}} and {{NEXT_PUBLIC_SUPABASE_ANON_KEY}}
// placeholders in the HTML with their env values at build time so the SPA
// can talk to the same Sovereign Supabase project as the Next.js OS.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, '..')
const sourcePath = join(repoRoot, 'public', 'index.html')
const outputPath = join(repoRoot, 'lib', 'wellness-spa-html.ts')

const raw = readFileSync(sourcePath, 'utf-8')

const substitutions = {
  '{{NEXT_PUBLIC_SUPABASE_URL}}': process.env.NEXT_PUBLIC_SUPABASE_URL ?? '',
  '{{NEXT_PUBLIC_SUPABASE_ANON_KEY}}': process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '',
}

let substituted = raw
for (const [token, value] of Object.entries(substitutions)) {
  substituted = substituted.split(token).join(value)
}

const base64 = Buffer.from(substituted, 'utf-8').toString('base64')

const banner = `// Auto-generated by scripts/embed-spa.mjs. Do not edit by hand.
// Re-run \`node scripts/embed-spa.mjs\` after changing public/index.html.
`

const content = `${banner}
// Source: public/index.html (${substituted.length} bytes after env substitution)
const ENCODED =
  '${base64}'

export const WELLNESS_SPA_HTML = Buffer.from(ENCODED, 'base64').toString('utf-8')
`

writeFileSync(outputPath, content, 'utf-8')

const sub = Object.entries(substitutions)
  .map(([k, v]) => `${k}=${v ? '[set]' : '[empty]'}`)
  .join(' ')
console.log(
  `[embed-spa] ${raw.length} bytes -> ${outputPath} (${base64.length} base64 chars) ${sub}`,
)
