import InsightCard from '@/components/InsightCard'
import InsightRefreshButton from '@/components/InsightRefreshButton'
import { requireConsumer } from '@/lib/consumer'

export default async function InsightsTab() {
  const { supabase, profile } = await requireConsumer()

  const { data: latest } = await supabase
    .from('daily_insights')
    .select('id, insight_text, generated_at')
    .eq('consumer_id', profile.id)
    .order('generated_at', { ascending: false })
    .limit(7)

  const items = latest ?? []
  const newest = items[0]
  const ageHours = newest
    ? (Date.now() - new Date(newest.generated_at as string).getTime()) / (1000 * 60 * 60)
    : null

  return (
    <div className="space-y-8">
      <header>
        <p className="heading-ui text-gold">Daily Insight</p>
        <h1 className="heading-display mt-2 text-3xl text-bone">
          A single read on your longevity vector.
        </h1>
        <p className="mt-2 max-w-2xl text-sm text-mist">
          Generated by Claude using your bio age inputs, tier and recent protocol
          history. Regenerates automatically every 20 hours.
        </p>
      </header>

      <InsightCard
        insight={(newest?.insight_text as string | undefined) ?? null}
        generatedAt={(newest?.generated_at as string | undefined) ?? null}
      />
      <InsightRefreshButton ageHours={ageHours} />

      <section>
        <p className="heading-ui text-gold">Recent Insights</p>
        {items.length <= 1 ? (
          <p className="mt-3 text-sm text-mist">
            History will populate as new insights are generated each day.
          </p>
        ) : (
          <ul className="mt-4 space-y-3">
            {items.slice(1).map((row) => (
              <li key={row.id as string} className="card p-4 text-sm">
                <p className="heading-ui text-mist">
                  {new Date(row.generated_at as string).toLocaleString(undefined, {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                  })}
                </p>
                <p className="mt-2 text-bone">{row.insight_text as string}</p>
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  )
}
